services:
  webapp:
    build: .
    container_name: pebble_bot
    image: pebble_bot
    env_file:
      - .env
    environment:
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
        REDDIT_SECRET_KEY=${REDDIT_SECRET_KEY}
        REDDIT_USERNAME=${REDDIT_USERNAME}
        REDDIT_PASSWORD=${REDDIT_PASSWORD}
        DISCORD_TOKEN=${DISCORD_TOKEN}
        SUPABASE_URL=${SUPABASE_URL}
        SUPABASE_KEY=${SUPABASE_KEY}
        DEV_GUILD_ID=${DEV_GUILD_ID}

